const $=s=>document.querySelector(s);
const KEY='tgProgress';
const META_PATTERNS=[/what should/i,/would you like/i,/how should/i,/what happens if/i,/should the site/i,/how should we/i,/what would you prefer/i,/which implementation/i,/what content should/i];
const defaults={version:3,xp:0,completed:[],favorites:[],difficult:[],incorrect:{},goal:30,streak:0,longest:0,lastLearningDate:null,dailyXp:0,dailyDate:null,achievements:[],lessonState:null,reviewStats:{},vocabSeen:[],settings:{sound:false}};
function loadState(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');const s={...defaults,...raw};s.completed=Array.isArray(s.completed)?s.completed:[];s.favorites=Array.isArray(s.favorites)?s.favorites:[];s.difficult=Array.isArray(s.difficult)?s.difficult:[];s.incorrect=s.incorrect&&typeof s.incorrect==='object'&&!Array.isArray(s.incorrect)?s.incorrect:{};s.achievements=Array.isArray(s.achievements)?s.achievements:[];s.vocabSeen=Array.isArray(s.vocabSeen)?s.vocabSeen:[];s.reviewStats=s.reviewStats&&typeof s.reviewStats==='object'?s.reviewStats:{};s.settings={...defaults.settings,...(s.settings||{})};return s}catch(e){localStorage.removeItem(KEY);return {...defaults}}}
let state=loadState();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const verifiedVocab=()=>VOCAB.filter(v=>v.verificationStatus==='verified');
const lessonById=id=>LESSONS.find(l=>l.id===id);
const lessonIndex=id=>LESSONS.findIndex(l=>l.id===id);
const isLessonComplete=id=>state.completed.includes(id);
const unlocked=i=>i===0||isLessonComplete(LESSONS[i-1].id);
function todayKey(){return new Date().toISOString().slice(0,10)}
function yesterdayKey(){const d=new Date();d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)}
function touchLearning(){const t=todayKey();if(state.dailyDate!==t){state.dailyDate=t;state.dailyXp=0;if(state.lastLearningDate===yesterdayKey())state.streak=(state.streak||0)+1;else if(state.lastLearningDate!==t)state.streak=1;state.longest=Math.max(state.longest||0,state.streak);state.lastLearningDate=t}}
function awardXP(amount,reason='learning'){if(!amount)return 0;touchLearning();state.xp+=amount;state.dailyXp+=amount;checkAchievements();save();return amount}
function levelInfo(){const level=Math.floor(state.xp/100)+1;const floor=(level-1)*100;return{level,name:level===1?'Beginner':level===2?'Learner':level===3?'Conversational Beginner':level===4?'Everyday Speaker':'Taishanese Learner',into:state.xp-floor,next:100}}
function achievement(id,title,description){if(state.achievements.includes(id))return;state.achievements.push(id);state.xp+=10;state.dailyXp+=10;const e=document.createElement('div');e.className='achievement-toast';e.innerHTML='<b>Achievement unlocked</b><strong>'+esc(title)+'</strong><span>'+esc(description)+'</span>';document.body.appendChild(e);setTimeout(()=>e.remove(),3000)}
function checkAchievements(){if(state.completed.length>=1)achievement('first','First Lesson','You completed your first lesson.');if(state.vocabSeen.length>=10)achievement('words10','10 Words Learned','You have practiced ten vocabulary items.');if(state.streak>=3)achievement('streak3','Three-Day Streak','You practiced meaningfully for three days in a row.');if(state.completed.length>=4)achievement('unit1','First Unit','You completed the first four lessons.');if(Object.keys(state.incorrect).length>=10)achievement('ten-correct','Persistent Practice','You have worked through ten distinct mistakes.');}
const nav=[['Home','home'],['Learn','learn'],['Vocabulary','vocabulary'],['Review','review'],['Pronunciation','pronunciation'],['Practice','practice'],['Progress','progress'],['Culture','culture'],['Phrasebook','phrases'],['Settings','settings']];
function shell(title,html){document.title=title+' · TaishaneseGo';$('#app').innerHTML='<div class="shell"><aside class="side"><div class="brand">台山<b>Go</b></div><nav>'+nav.map(n=>'<a class="'+(location.hash==='#'+n[1]?'active':'')+'" href="#'+n[1]+'">'+n[0]+'</a>').join('')+'</nav></aside><main class="main page-enter">'+html+'</main></div>';}
function courseStats(){return{done:state.completed.length,total:LESSONS.length,pct:LESSONS.length?Math.round(state.completed.length/LESSONS.length*100):0}}
function resumeCard(){const s=state.lessonState;if(!s||s.completed)return '';const l=lessonById(s.lessonId);if(!l)return '';return '<div class="card resume"><div><p class="tag">Resume</p><h2>'+esc(l.title)+'</h2><p>Question '+Math.min(s.currentQuestionIndex+1,l.exercises.length)+' of '+l.exercises.length+' · '+Math.round((s.answeredQuestions.length/l.exercises.length)*100)+'% answered</p></div><button onclick="resumeLesson()">Resume lesson</button></div>'}
function home(){const st=courseStats(),lv=levelInfo();shell('Home','<div class="top"><div><p>TAISHANESE · 台山話 · HOISANESE</p><h1>Learn Taishanese, one step at a time.</h1><p>Short, source-linked lessons with deterministic progress and review.</p></div><button onclick="location.hash=\'#learn\'">Continue Learning</button></div>'+resumeCard()+'<div class="grid"><div class="card"><p>Streak</p><div class="stat">'+state.streak+' days</div><p>Best: '+state.longest+'</p></div><div class="card"><p>Level '+lv.level+' · '+lv.name+'</p><div class="stat">'+state.xp+' XP</div><div class="progress"><i style="width:'+lv.into+'%"></i></div></div><div class="card"><p>Daily goal</p><div class="stat">'+state.dailyXp+' / '+state.goal+' XP</div><div class="progress"><i style="width:'+Math.min(100,state.dailyXp/state.goal*100)+'%"></i></div></div><div class="card"><p>Course</p><div class="stat">'+st.pct+'%</div><div class="progress"><i style="width:'+st.pct+'%"></i></div></div></div><h2>Course path</h2>'+courseMap())}
function courseMap(){return '<div class="course">'+COURSE_UNITS.map((u,ui)=>{const ls=LESSONS.filter(l=>l.unitId===u.id);const unitDone=ls.length>0&&ls.every(l=>isLessonComplete(l.id));const unitOpen=ls.length>0&&unlocked(lessonIndex(ls[0].id));return '<section class="unit card"><div class="unit-head"><div><p class="tag">Unit '+(ui+1)+'</p><h2>'+esc(u.title.replace(/^Unit \d+ — /,''))+'</h2><p>'+esc(u.description)+'</p></div><span class="verify">'+(u.comingSoon?'In preparation':unitDone?'Complete':unitOpen?'Available':'Locked')+'</span></div>'+ (ls.length?'<div class="course">'+ls.map(l=>{const i=lessonIndex(l.id),done=isLessonComplete(l.id),open=unlocked(i);return '<div class="card lesson '+(!open?'locked':'')+'"><div class="node '+(done?'done':open?'open':'')+'">'+(done?'✓':i+1)+'</div><div><b>'+esc(l.unit)+'</b><h3>'+esc(l.title)+'</h3><p>'+esc(l.description)+'</p><small>Objective: '+esc(l.objective)+'</small></div>'+(open?'<button onclick="startLesson(\''+l.id+'\')">'+(done?'Review':'Start')+'</button>':'<span>Locked</span>')+'</div>'}).join('')+'</div>':'<div class="notice">No learner lesson is published here yet. New language content is added only after source review.</div>')+'</section>'}).join('')+'</div>'}
function learn(){shell('Learn','<h1>Learn</h1><p>Lessons introduce a small set of verified source-backed language, then make you use it in different ways.</p>'+courseMap())}
function validQuestion(q){if(!q||!q.id||!q.type||!q.prompt)return false;if(META_PATTERNS.some(p=>p.test(q.prompt)))return false;return ['translation','multipleChoice','matching','listening','fillBlank','wordOrder','conversation'].includes(q.type)}
function validateLessons(){LESSONS.forEach(l=>{l.exercises=l.exercises.filter(validQuestion)})}
function startLesson(id){const i=lessonIndex(id);if(i<0||!unlocked(i))return;const l=LESSONS[i];state.lessonState={lessonId:l.id,currentLesson:i,currentQuestionIndex:0,answeredQuestions:[],score:0,xpEarned:0,completed:false,lessonProgress:0,attempts:0,streak:state.streak,hearts:4,draft:null};save();location.hash='lesson';renderLesson()}
function resumeLesson(){if(!state.lessonState)return;location.hash='lesson';renderLesson()}
function qHeader(l,s){const total=l.exercises.length;const pct=Math.round((s.answeredQuestions.length/total)*100);return '<div class="lesson-head"><button class="alt" onclick="location.hash=\'#learn\'">Exit</button><div style="flex:1"><p>Question '+(s.currentQuestionIndex+1)+' of '+total+'</p><div class="progress"><i style="width:'+pct+'%"></i></div></div><span class="hearts">'+('♥'.repeat(s.hearts)+'♡'.repeat(Math.max(0,4-s.hearts)))+'</span></div>'}
function renderLesson(){const s=state.lessonState;if(!s){location.hash='learn';return}const l=lessonById(s.lessonId);if(!l){state.lessonState=null;save();location.hash='learn';return}if(s.currentQuestionIndex>=l.exercises.length){finishLesson();return}const q=l.exercises[s.currentQuestionIndex];const body=renderQuestion(q,s);shell(l.title,qHeader(l,s)+'<div class="exercise question-in"><p class="tag">'+esc(l.objective)+'</p><span class="verify">'+esc(q.type)+'</span><h2>'+esc(q.prompt)+'</h2>'+body+'<div id="feedback"></div></div>');}
function renderQuestion(q,s){if(q.type==='matching')return '<div class="matching">'+q.pairs.map((p,i)=>'<label class="match-row"><b>'+esc(p[0])+'</b><select data-match="'+i+'"><option value="">Choose meaning</option>'+q.pairs.map(x=>'<option value="'+esc(x[1])+'">'+esc(x[1])+'</option>').join('')+'</select></label>').join('')+'</div><button onclick="submitQuestion()">Check</button>';
if(q.type==='wordOrder'){return '<div class="word-bank">'+q.tokens.map((t,i)=>'<button class="alt token" onclick="addToken('+i+')">'+esc(t)+'</button>').join('')+'</div><div id="orderDraft" class="order-draft">'+((s.draft||[]).map(esc).join(' · ')||'Select the words in order')+'</div><button class="alt" onclick="clearDraft()">Reset</button> <button onclick="submitQuestion()">Check</button>'}
if(q.type==='fillBlank')return '<div class="fill"><input id="answerInput" class="search" autocomplete="off" placeholder="Type the answer"></div><button onclick="submitQuestion()">Check</button>';
if(q.type==='listening'){const v=VOCAB.find(x=>q.vocabularyIds?.includes(x.id));return '<div class="audio-state">'+(v?.audio?'<button onclick="playAudio(\''+esc(v.audio)+'\')">Play audio</button>':'<span>Audio unavailable for this item.</span>')+'</div><div class="options">'+q.options.map((o,i)=>'<button class="option" onclick="chooseOption('+i+')">'+esc(o)+'</button>').join('')+'</div>'}
return '<div class="options">'+q.options.map((o,i)=>'<button class="option" onclick="chooseOption('+i+')">'+esc(o)+'</button>').join('')+'</div>'}
function currentQuestion(){const s=state.lessonState;return s?lessonById(s.lessonId).exercises[s.currentQuestionIndex]:null}
function chooseOption(i){const q=currentQuestion();if(!q||state.lessonState.answeredQuestions.includes(state.lessonState.currentQuestionIndex))return;document.querySelectorAll('.option').forEach((b,j)=>{b.disabled=true;if(j===i)b.classList.add('selected')});submitQuestion(i)}
function addToken(i){const s=state.lessonState,q=currentQuestion();if(!s||q.type!=='wordOrder'||s.answeredQuestions.includes(s.currentQuestionIndex))return;s.draft=s.draft||[];if(s.draft.includes(q.tokens[i]))return;s.draft.push(q.tokens[i]);$('#orderDraft').textContent=s.draft.join(' · ');save()}
function clearDraft(){if(state.lessonState){state.lessonState.draft=[];save();$('#orderDraft').textContent='Select the words in order'}}
function submitQuestion(optionIndex){const s=state.lessonState,q=currentQuestion();if(!s||!q||s.answeredQuestions.includes(s.currentQuestionIndex))return;let answer=optionIndex;if(q.type==='fillBlank')answer=($('#answerInput')?.value||'').trim();if(q.type==='matching'){answer={};document.querySelectorAll('[data-match]').forEach(el=>answer[el.dataset.match]=el.value)}if(q.type==='wordOrder')answer=s.draft||[];let ok;if(q.type==='matching')ok=q.pairs.every((p,i)=>answer[i]===p[1]);else if(q.type==='wordOrder')ok=JSON.stringify(answer)===JSON.stringify(q.correctOrder);else ok=String(answer).trim().toLowerCase()===String(q.correctAnswer).trim().toLowerCase();s.answeredQuestions.push(s.currentQuestionIndex);s.attempts++;if(ok)s.score++;else{s.hearts=Math.max(0,s.hearts-1);const key=q.id;state.incorrect[key]=(state.incorrect[key]||0)+1}const qxp=ok?3:1;s.xpEarned+=qxp;awardXP(qxp);(q.vocabularyIds||[]).forEach(id=>{if(!state.vocabSeen.includes(id))state.vocabSeen.push(id)});s.lessonProgress=Math.round(s.answeredQuestions.length/qTotal(s)*100);s.draft=null;save();document.querySelectorAll('.option').forEach((b,j)=>{b.disabled=true;if(q.options&&q.options[j]===q.correctAnswer)b.classList.add('correct');if(q.options&&q.options[j]===answer&&!ok)b.classList.add('wrong')});const f=$('#feedback');if(f)f.innerHTML='<div class="feedback '+(ok?'good':'bad')+'"><b>'+(ok?'Correct':'Not quite')+'</b><p>'+esc(q.explanation)+'</p>'+(q.type==='fillBlank'||q.type==='wordOrder'||q.type==='matching'?'<p><b>Answer:</b> '+esc(answerText(q))+'</p>':'')+'<button onclick="continueLesson()">'+(s.currentQuestionIndex===qTotal(s)-1?'Finish lesson':'Continue')+'</button></div>';document.querySelector('.exercise')?.classList.add(ok?'success':'error');if(s.hearts===0&&s.currentQuestionIndex<qTotal(s)-1){setTimeout(()=>{s.hearts=4;save()},300)}}
function qTotal(s){return lessonById(s.lessonId).exercises.length}
function answerText(q){if(q.type==='matching')return q.pairs.map(p=>p[1]).join(', ');if(q.type==='wordOrder')return q.correctOrder.join(' ');return q.correctAnswer}
function continueLesson(){const s=state.lessonState;if(!s||!s.answeredQuestions.includes(s.currentQuestionIndex))return;if(s.currentQuestionIndex<qTotal(s)-1){s.currentQuestionIndex++;s.lessonProgress=Math.round(s.answeredQuestions.length/qTotal(s)*100);save();renderLesson()}else finishLesson()}
function finishLesson(){const s=state.lessonState,l=lessonById(s.lessonId);if(!s||s.completed)return;s.completed=true;s.lessonProgress=100;const first=!state.completed.includes(l.id);if(first)state.completed.push(l.id);const completionXP=first?15:0;s.xpEarned+=completionXP;if(completionXP)awardXP(completionXP,'lesson');else save();checkAchievements();save();const accuracy=Math.round(s.score/l.exercises.length*100);const next=LESSONS[s.currentLesson+1];const unlockedNext=next&&!isLessonComplete(next.id);shell('Lesson Complete','<div class="card completion"><div class="reward">✓</div><h1>Lesson complete</h1><div class="stat">+'+s.xpEarned+' XP</div><p>Accuracy: '+accuracy+'% · Questions: '+l.exercises.length+' · Correct: '+s.score+'</p><p>Meaningful learning today: '+state.dailyXp+' / '+state.goal+' XP '+(state.dailyXp>=state.goal?'— goal complete.':'')+'</p><div class="progress"><i style="width:100%"></i></div>'+(unlockedNext?'<p class="unlock">Unlocked: '+esc(next.title)+'</p>':'')+'<div class="row"><button onclick="goNextLesson()">'+(unlockedNext?'Next lesson':'Back to course')+'</button><button class="alt" onclick="finishAndReview()">Review words</button></div></div>');state.lessonState=s;save();confetti()}
function goNextLesson(){const s=state.lessonState,i=s? s.currentLesson+1:LESSONS.length;if(i<LESSONS.length&&unlocked(i))startLesson(LESSONS[i].id);else{state.lessonState=null;save();location.hash='learn'}}
function finishAndReview(){state.lessonState=null;save();location.hash='review'}
function confetti(){for(let i=0;i<18;i++){const e=document.createElement('i');e.className='confetti';e.style.left=Math.random()*100+'%';e.style.animationDelay=Math.random()*.2+'s';document.body.appendChild(e);setTimeout(()=>e.remove(),1100)}}
function vocabulary(){shell('Vocabulary','<h1>Vocabulary</h1><p>Browse source-linked vocabulary that has entered the learner course.</p><input class="search" id="search" placeholder="Search Taishanese, romanization, English, or category"><div id="words" class="vocab"></div>');$('#search').oninput=()=>showVocab();showVocab()}
window.showVocab=()=>{const q=($('#search')?.value||'').toLowerCase();const a=verifiedVocab().filter(v=>JSON.stringify(v).toLowerCase().includes(q));$('#words').innerHTML=a.map(v=>'<div class="card"><b>'+esc(v.category)+'</b><h2>'+esc(v.taishanese)+'</h2><p>'+esc(v.romanization)+' · '+esc(v.english)+'</p><p>'+(v.exampleSentence?esc(v.exampleSentence):'No example published')+'</p><span class="verify">'+esc(v.verificationStatus)+'</span><div class="row">'+(v.audio?'<button onclick="playAudio(\''+esc(v.audio)+'\')">Audio</button>':'<button class="alt" disabled>Audio unavailable</button>')+'<button class="alt" onclick="toggleFav(\''+esc(v.id)+'\')">'+(state.favorites.includes(v.id)?'★ Favorite':'☆ Favorite')+'</button></div></div>').join('')||'<div class="notice">No matching verified vocabulary.</div>'};
window.toggleFav=id=>{state.favorites.includes(id)?state.favorites=state.favorites.filter(x=>x!==id):state.favorites.push(id);save();showVocab()};
function playAudio(src){if(!src)return;try{new Audio(src).play()}catch(e){}}
function reviewPool(){const recent=state.vocabSeen.slice(-10).map(id=>VOCAB.find(v=>v.id===id)).filter(Boolean);const difficult=state.difficult.map(id=>VOCAB.find(v=>v.id===id)).filter(Boolean);const incorrect=Object.keys(state.incorrect).map(qid=>{const q=LESSONS.flatMap(l=>l.exercises).find(x=>x.id===qid);return q?.vocabularyIds||[]}).flat().map(id=>VOCAB.find(v=>v.id===id)).filter(Boolean);const fav=state.favorites.map(id=>VOCAB.find(v=>v.id===id)).filter(Boolean);return{recent,difficult,incorrect,favorites:fav}}
function review(){const pools=reviewPool();shell('Review','<h1>Review</h1><p>Practice words you have actually encountered. Correct review answers give limited XP so review supports learning without becoming an XP farm.</p><div class="grid">'+Object.entries(pools).map(([k,a])=>'<div class="card"><p>'+k+'</p><div class="stat">'+a.length+'</div><button onclick="startReview(\''+k+'\')" '+(!a.length?'disabled':'')+'>Review</button></div>').join('')+'</div><div class="notice">Review rewards are capped per vocabulary item per day.</div>')}
window.startReview=mode=>{const pool=reviewPool()[mode]||[];if(!pool.length)return;let i=0,correct=0,earned=0;function draw(){const v=pool[i%pool.length];shell('Review','<div class="lesson-head"><div style="flex:1"><p>Review · '+(i+1)+' of '+pool.length+'</p><div class="progress"><i style="width:'+Math.round(i/pool.length*100)+'%"></i></div></div></div><div class="exercise"><p class="tag">'+esc(v.category)+'</p><h2>'+esc(v.english)+'</h2><p>Choose the Taishanese form.</p><div class="options">'+shuffle([v.taishanese,...pool.filter(x=>x.id!==v.id).slice(0,3).map(x=>x.taishanese)]).map((o,n)=>'<button class="option" onclick="reviewAnswer(\''+esc(v.id)+'\',\''+esc(o)+'\')">'+esc(o)+'</button>').join('')+'</div><div id="feedback"></div></div>')}window.reviewAnswer=(id,answer)=>{const v=VOCAB.find(x=>x.id===id),ok=v&&answer===v.taishanese;if(ok)correct++;let key=todayKey()+':'+id;const used=state.reviewStats[key]||0;let xp=ok&&used<2?2:0;if(xp){state.reviewStats[key]=used+1;earned+=xp;awardXP(xp,'review')}if(v&&!state.vocabSeen.includes(v.id))state.vocabSeen.push(v.id);save();const f=$('#feedback');document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.textContent===v.taishanese)b.classList.add('correct');if(b.textContent===answer&&!ok)b.classList.add('wrong')});if(f)f.innerHTML='<div class="feedback '+(ok?'good':'bad')+'"><b>'+(ok?'Correct':'Keep practicing')+'</b><p>'+esc(v.taishanese)+' · '+esc(v.romanization)+'</p><button onclick="'+(i+1<pool.length?'nextReview()':'endReview()')+'">'+(i+1<pool.length?'Continue':'Finish review')+'</button></div>';};window.nextReview=()=>{i++;draw()};window.endReview=()=>{achievement('review','Review Session','You completed a focused review session.');save();shell('Review Complete','<div class="card completion"><h1>Review complete</h1><div class="stat">+'+earned+' XP</div><p>'+correct+' correct out of '+pool.length+'.</p><button onclick="location.hash=\'#review\'">Back to review</button></div>')};draw()};
function flashcards(){const pool=verifiedVocab();if(!pool.length){shell('Flashcards','<h1>Flashcards</h1><div class="notice">No verified vocabulary is available yet.</div>');return}let i=0;function draw(){const v=pool[i%pool.length];shell('Flashcards','<h1>Flashcards</h1><p>Flip the card, then mark difficult words for review.</p><div class="flash" id="flash"><div class="front"><h2>'+esc(v.english)+'</h2></div><div class="back"><h2>'+esc(v.taishanese)+'</h2><p>'+esc(v.romanization)+'</p></div></div><div class="row"><button onclick="nextCard()">Next</button><button class="alt" onclick="hardCard(\''+esc(v.id)+'\')">Mark difficult</button></div>')}window.nextCard=()=>{i++;draw();};window.hardCard=id=>{if(!state.difficult.includes(id))state.difficult.push(id);save();nextCard()};draw();setTimeout(()=>$('#flash')&&($('#flash').onclick=()=>$('#flash').classList.toggle('flipped')),0)}
function pronunciation(){shell('Pronunciation','<h1>Pronunciation</h1><div class="card"><h2>Transcription system</h2><p>'+esc(PRONUNCIATION.system)+'</p><p>'+esc(PRONUNCIATION.notes.join(' '))+'</p><span class="verify">'+esc(PRONUNCIATION.status)+'</span></div><div class="card"><h2>Audio</h2><p>Authentic Taishanese recordings have not been added to these entries yet. Audio controls stay disabled rather than substituting another Chinese variety.</p></div>')}
function practice(){shell('Daily Practice','<h1>Daily Practice</h1><div class="card"><h2>'+state.dailyXp+' / '+state.goal+' XP today</h2><div class="progress"><i style="width:'+Math.min(100,state.dailyXp/state.goal*100)+'%"></i></div><p>'+ (state.dailyXp>=state.goal?'Daily goal complete.':'Earn XP by answering lesson or review questions.')+'</p><div class="row"><button onclick="location.hash=\'#review\'">Review</button><button class="alt" onclick="location.hash=\'#learn\'">Learn</button></div></div>')}
function progress(){const st=courseStats(),lv=levelInfo();shell('Progress','<h1>Progress</h1><div class="grid"><div class="card"><p>Level '+lv.level+' · '+lv.name+'</p><div class="stat">'+state.xp+' XP</div><div class="progress"><i style="width:'+lv.into+'%"></i></div><small>'+lv.next+' XP per level</small></div><div class="card"><p>Streak</p><div class="stat">'+state.streak+'</div><p>Best: '+state.longest+' days</p></div><div class="card"><p>Course</p><div class="stat">'+st.pct+'%</div><div class="progress"><i style="width:'+st.pct+'%"></i></div></div><div class="card"><p>Achievements</p><div class="stat">'+state.achievements.length+'</div></div></div><h2>Achievements</h2><div class="vocab">'+[['first','First Lesson'],['words10','10 Words Learned'],['streak3','Three-Day Streak'],['unit1','First Unit'],['review','Review Session'],['ten-correct','Persistent Practice']].map(a=>'<div class="card '+(state.achievements.includes(a[0])?'unlocked':'locked')+'"><h3>'+a[1]+'</h3><p>'+(state.achievements.includes(a[0])?'Unlocked':'Keep learning to unlock this.')+'</p></div>').join('')+'</div>')}
function culture(){shell('Culture','<h1>Taishan & culture</h1><div class="card"><h2>A distinct language</h2><p>Taishanese, also called Toisanese or Hoisanese, is associated with Taishan in Guangdong and with Sze Yap communities overseas.</p><h2>Variation matters</h2><p>The course keeps source information attached to each entry so regional or family differences can be reviewed instead of silently flattened.</p></div>')}
function phrases(){const a=PHRASES.filter(p=>p.verificationStatus==='verified');shell('Phrasebook','<h1>Phrasebook</h1><div class="vocab">'+a.map(p=>'<div class="card"><b>'+esc(p.category)+'</b><h2>'+esc(p.taishanese)+'</h2><p>'+esc(p.romanization||'Romanization not published on this source page')+'</p><p>'+esc(p.english)+'</p><span class="verify">'+esc(p.verificationStatus)+'</span></div>').join('')+'</div>')}
function settings(){shell('Settings','<h1>Settings</h1><div class="card"><h2>Daily goal</h2><div class="row">'+[10,20,30,50].map(n=>'<button class="alt '+(state.goal===n?'selected':'')+'" onclick="setGoal('+n+')">'+n+' XP</button>').join('')+'</div><h2>Appearance</h2><button onclick="toggleTheme()">Toggle dark / light mode</button><h2>Developer content review</h2><p>This review screen is intentionally outside the learner navigation.</p><button class="alt" onclick="location.hash=\'#content-review\'">Open content review</button><h2>Privacy</h2><p>Learning progress and reviewer notes are stored locally in this browser.</p><button class="alt" onclick="resetProgress()">Reset progress</button></div>')}
window.toggleTheme=()=>{document.body.classList.toggle('dark');localStorage.setItem('tgTheme',document.body.classList.contains('dark')?'dark':'light')};window.setGoal=n=>{state.goal=n;save();settings()};window.resetProgress=()=>{if(confirm('Reset all learner progress on this device?')){localStorage.removeItem(KEY);location.reload()}};
function contentReview(){const saved=JSON.parse(localStorage.getItem('tgReviews')||'{}');shell('Content Review','<h1>Content Review</h1><div class="notice">Developer/editor workflow. Changes here are local review notes; they do not rewrite the language data file.</div><div class="course">'+VOCAB.map((v,i)=>'<div class="card"><b>'+esc(v.id)+' · '+esc(v.category)+'</b><h2>'+esc(v.taishanese)+'</h2><p>'+esc(v.romanization)+' · '+esc(v.english)+'</p><p>Example: '+esc(v.exampleSentence||'None')+'<br>Source: '+esc(v.source||'Not supplied')+'<br>Audio: '+esc(v.audio||'None')+'</p><span class="verify">'+esc(saved[v.id]?.status||v.verificationStatus)+'</span><textarea id="note'+i+'" class="search" placeholder="Reviewer correction / note">'+esc(saved[v.id]?.note||'')+'</textarea><div class="row"><button onclick="reviewItem(\''+esc(v.id)+'\',\'verified\','+i+')">Confirm</button><button class="alt" onclick="reviewItem(\''+esc(v.id)+'\',\'needs_review\','+i+')">Needs correction</button><button class="alt" onclick="reviewItem(\''+esc(v.id)+'\',\'unverified\','+i+')">Unverified</button></div></div>').join('')+'</div>')}
window.reviewItem=(id,status,i)=>{const reviews=JSON.parse(localStorage.getItem('tgReviews')||'{}');reviews[id]={status,note:$('#note'+i)?.value||'',date:new Date().toISOString()};localStorage.setItem('tgReviews',JSON.stringify(reviews));contentReview()};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function router(){validateLessons();const r=location.hash.slice(1)||'home';const fn={home,learn,vocabulary,review,pronunciation,flashcards,practice,progress,culture,phrases,settings,'content-review':contentReview,lesson:renderLesson}[r]||home;if(r==='lesson'&&!state.lessonState)return location.hash='learn';fn()}
if(localStorage.getItem('tgTheme')==='dark')document.body.classList.add('dark');addEventListener('hashchange',router);router();