const $=s=>document.querySelector(s);
const state=Object.assign({xp:0,completed:[],favorites:[],difficult:[],goal:10,streak:1,longest:1},JSON.parse(localStorage.getItem('tgProgress')||'{}'));
function save(){localStorage.setItem('tgProgress',JSON.stringify(state))}
const nav=[['Home','home'],['Learn','learn'],['Vocabulary','vocabulary'],['Flashcards','flashcards'],['Practice','practice'],['Progress','progress'],['Culture','culture'],['Phrasebook','phrases'],['Settings','settings']];
function shell(title,html){document.title=title+' · TaishaneseGo';$('#app').innerHTML='<div class="shell"><aside class="side"><div class="brand">台山<b>Go</b></div><nav>'+nav.map(n=>'<a href="#'+n[1]+'">'+n[0]+'</a>').join('')+'</nav></aside><main class="main">'+html+'</main></div>'}
function open(i){return i===0||state.completed.includes(LESSONS[i-1].id)}
function home(){let pct=Math.round(state.completed.length/LESSONS.length*100);shell('Home','<div class="top"><div><p>TAISHANESE · 台山話 · HOISANESE</p><h1>Learn Taishanese, one step at a time.</h1><p>An accuracy-first learning platform. Your progress stays on this device.</p></div><button onclick="location.hash=\'#learn\'">Continue Learning</button></div><div class="grid"><div class="card"><p>Streak</p><div class="stat">'+state.streak+' days</div></div><div class="card"><p>XP</p><div class="stat">'+state.xp+'</div></div><div class="card"><p>Lessons</p><div class="stat">'+state.completed.length+'</div></div><div class="card"><p>Course</p><div class="stat">'+pct+'%</div><div class="progress"><i style="width:'+pct+'%"></i></div></div></div><h2>Course path</h2><div class="course">'+LESSONS.map((l,i)=>'<div class="card lesson '+(!open(i)?'locked':'')+'"><div class="node '+(state.completed.includes(l.id)?'done':open(i)?'open':'')+'">'+(state.completed.includes(l.id)?'✓':i+1)+'</div><div><b>'+l.unit+'</b><h3>'+l.title+'</h3><p>'+l.description+'</p></div>'+ (open(i)?'<button onclick="startLesson('+i+')">Start</button>':'<span>Locked</span>')+'</div>').join('')+'</div>')}
function learn(){shell('Learn','<h1>Learn</h1><p>Complete each lesson to unlock the next.</p><div class="course">'+LESSONS.map((l,i)=>'<div class="card lesson '+(!open(i)?'locked':'')+'"><div class="node '+(state.completed.includes(l.id)?'done':open(i)?'open':'')+'">'+(state.completed.includes(l.id)?'✓':i+1)+'</div><div><b>'+l.unit+'</b><h3>'+l.title+'</h3><p>'+l.description+'</p></div>'+ (open(i)?'<button onclick="startLesson('+i+')">'+(state.completed.includes(l.id)?'Review':'Start')+'</button>':'<span>🔒</span>')+'</div>').join('')+'</div>')}
function startLesson(i){let q=0,score=0;function draw(){let e=LESSONS[i].exercises[q];shell(LESSONS[i].title,'<p>Question '+(q+1)+' of '+LESSONS[i].exercises.length+'</p><div class="exercise"><h2>'+e.question+'</h2><p>'+e.note+'</p><div class="options">'+e.options.map((o,n)=>'<button class="option" onclick="answer('+i+','+q+','+n+')">'+o+'</button>').join('')+'</div><p id="feedback"></p></div>')}window.answer=(i,q,n)=>{let e=LESSONS[i].exercises[q],ok=n===e.answer;document.querySelectorAll('.option').forEach((b,j)=>{b.disabled=true;if(j===e.answer)b.classList.add('correct');if(j===n&&!ok)b.classList.add('wrong')});$('#feedback').textContent=(ok?'Correct! ':'Not quite. ')+e.explanation;if(ok)score++;setTimeout(()=>{q++;q<LESSONS[i].exercises.length?draw():finish(i,score)},850)};draw()}
function finish(i,score){if(!state.completed.includes(LESSONS[i].id)){state.completed.push(LESSONS[i].id);state.xp+=20;save()}shell('Complete','<div class="card"><h1>Lesson complete</h1><p>You got '+score+' out of '+LESSONS[i].exercises.length+' correct.</p><div class="stat">+20 XP</div><button onclick="location.hash=\'#learn\'">Back to Learn</button></div>')}
function vocabulary(){shell('Vocabulary','<h1>Vocabulary</h1><div class="notice">Accuracy policy: entries marked Needs verification are placeholders, not invented Taishanese.</div><input class="search" id="search" placeholder="Search vocabulary"><div class="tags">'+[...new Set(VOCAB.map(v=>v.category))].map(c=>'<button class="alt" onclick="showVocab(\''+c+'\')">'+c+'</button>').join('')+'</div><div id="words" class="vocab"></div>');$('#search').oninput=()=>showVocab('');showVocab('')}
window.showVocab=(cat)=>{let q=$('#search').value.toLowerCase();let a=VOCAB.filter(v=>(!cat||v.category===cat)&&JSON.stringify(v).toLowerCase().includes(q));$('#words').innerHTML=a.map(v=>'<div class="card"><b>'+v.category+'</b><h2>'+v.english+'</h2><p><b>'+v.taishanese+'</b><br>'+v.romanization+'</p><span class="verify">'+v.status+'</span><p>'+v.example+'</p><button class="alt" onclick="toggleFav(\''+v.id+'\')">'+(state.favorites.includes(v.id)?'★ Favorited':'☆ Favorite')+'</button></div>').join('')}
window.toggleFav=id=>{state.favorites.includes(id)?state.favorites=state.favorites.filter(x=>x!==id):state.favorites.push(id);save();showVocab('')}
function flashcards(){let i=0,pool=VOCAB;function draw(){let v=pool[i];shell('Flashcards','<h1>Flashcards</h1><p>Click the card to flip it.</p><div class="flash" id="flash"><div class="front"><h2>'+v.english+'</h2></div><div class="back"><h2>'+v.taishanese+'</h2><p>'+v.romanization+'</p><span class="verify">'+v.status+'</span></div></div><div class="row"><button onclick="nextCard()">Next</button><button class="alt" onclick="hardCard()">Mark difficult</button></div>');$('#flash').onclick=()=>$('#flash').classList.toggle('flipped')}window.nextCard=()=>{i=(i+1)%pool.length;draw()};window.hardCard=()=>{let id=pool[i].id;if(!state.difficult.includes(id))state.difficult.push(id);save();window.nextCard()};draw()}
function practice(){shell('Daily Practice','<h1>Daily Practice</h1><div class="card"><h2>'+state.goal+' minute goal</h2><p>Review flashcards, difficult words, and completed lessons.</p><button onclick="location.hash=\'#flashcards\'">Start reviewing</button></div>')}
function progress(){let pct=Math.round(state.completed.length/LESSONS.length*100);shell('Progress','<h1>Progress</h1><div class="grid"><div class="card"><div class="stat">'+pct+'%</div><p>Course complete</p><div class="progress"><i style="width:'+pct+'%"></i></div></div><div class="card"><div class="stat">'+state.completed.length+'/'+LESSONS.length+'</div><p>Lessons completed</p></div><div class="card"><div class="stat">'+state.xp+'</div><p>Total XP</p></div><div class="card"><div class="stat">'+state.difficult.length+'</div><p>Difficult words</p></div></div>')}
function culture(){shell('Culture','<h1>Taishan & culture</h1><div class="card"><h2>A distinct language variety</h2><p>Taishanese is associated with Taishan in Guangdong and is not simply Cantonese or Mandarin under another name.</p><h2>Communities around the world</h2><p>Taishanese-speaking migration played an important role in Chinese diaspora communities, including historic communities in North America.</p><h2>Respecting variation</h2><p>Pronunciation and vocabulary may vary by locality and family. This project is designed to document verified variation instead of guessing.</p></div>')}
function phrases(){shell('Phrasebook','<h1>Phrasebook</h1><div class="vocab">'+PHRASES.map(p=>'<div class="card"><b>'+p.category+'</b><h2>'+p.english+'</h2><p>'+p.taishanese+'<br>'+p.romanization+'</p><span class="verify">'+p.status+'</span></div>').join('')+'</div>')}
function settings(){shell('Settings','<h1>Settings</h1><div class="card"><h2>Appearance</h2><button onclick="toggleTheme()">Toggle dark / light mode</button><h2>Daily goal</h2><div class="row">'+[5,10,15,30].map(n=>'<button class="alt" onclick="setGoal('+n+')">'+n+' minutes</button>').join('')+'</div><h2>Privacy</h2><p>All progress is stored locally in your browser. No account is required.</p><button class="alt" onclick="resetProgress()">Reset progress</button></div>')}
window.toggleTheme=()=>{document.body.classList.toggle('dark');localStorage.setItem('tgTheme',document.body.classList.contains('dark')?'dark':'light')};window.setGoal=n=>{state.goal=n;save();settings()};window.resetProgress=()=>{if(confirm('Reset all TaishaneseGo progress on this device?')){localStorage.removeItem('tgProgress');location.reload()}};
function router(){let r=location.hash.slice(1)||'home';({home,learn,vocabulary,flashcards,practice,progress,culture,phrases,settings}[r]||home)()}if(localStorage.getItem('tgTheme')==='dark')document.body.classList.add('dark');addEventListener('hashchange',router);router();